credentials        = %local path to terraform keyfile%
project_id         = %PROJECT_ID%
region             = "us-east1"
zones              = ["us-east1-b"]
name               = %GKE cluster name%
machine_type       = "g1-small"
min_count          = 1
max_count          = 3
disk_size_gb       = 10
service_account    = %terraform service account%
initial_node_count = 1
db_instance_name   = %DB instance name%
db_name            = %DB name%
db_tier            = "db-f1-micro"
db_disk_size_gb    = 10
db_disk_type       = "PD_HDD"
db_user            = %DB user name%
db_password        = %DB password%
service_account_id = %service account for CloudSQL client%
kubernetes_sa_name = %additional service account for CLoudSQL client authentication%
schedule_topic_name = %pubsub schedule topic name%
schedule_subscription_name = %pubsub schedule subscription name%
schedule           = %pubsub schedule cron expression%
