---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "global-cluster-ip"
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: {{ .Chart.Name }}
spec:
  rules:
    - http:
        paths:
          - path:
            backend:
              serviceName: {{ .Chart.Name  }}
              servicePort: http
